# Generated by Django 3.2.21 on 2023-09-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_cartitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
    ]
