# Generated by Django 3.2.21 on 2023-09-18 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_remove_cart_product'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='app_Product',
        ),
    ]
