# Generated by Django 3.2.21 on 2023-10-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_auto_20230930_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=6)),
                ('is_expired', models.BooleanField(default=False)),
                ('discount_price', models.IntegerField(default=0)),
                ('minimum_amount', models.IntegerField(default=500)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.product')),
            ],
        ),
    ]
